spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ENC(oNPaGy1vhuDlCoB3N9qayC9by/HCMFba)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  mail:
    username: Perficient Library Prod <perficient.library@perficient.com>
server:
  port: 7000
  context-path: /
logging:
  config: classpath:logging/logback-prod.xml
library:
  sso:
    url: https://gdcsso.perficient.com/cas/login/?service=
    back-end.base-url: http://10.2.1.102:8000
    front-end.base-url: http://10.2.1.102:8080
    validate-url: https://gdcsso.perficient.com/cas/p3/serviceValidate
  upload:
    visit-url: http://10.2.1.102/static/
    upload-folder: /usr/local/uploads/
    max-file-size: 10485760
  schedule:
    mail:
      active: false
      expression: 0/30 * 8-19 * * ?
    advance-reminder:
      active: false
      expression: 0 0 1 * * ?
    overdue-reminder:
      active: false
      expression: 0 0 2 * * ?