spring:
  profiles:
    active: '@spring.profile.active@'
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
  http:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
  thymeleaf:
    mode: LEGACYHTML5
  mail:
    host: localhost
    default-encoding: UTF-8
logging:
  level:
    springfox.documentation: warn
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: warn